
### consultar todos los amigos
GET http://127.0.0.1:8000/Amigos

### consultar amigo
GET http://127.0.0.1:8000/Amigos/2

### crear amigo
POST http://127.0.0.1:8000/Amigos
Content-Type: application/json

{
    "nombre": "Pepe",
    "apodo" : "Pepito Flores"
    "email": "pepe23@yahoo.com",
    "telefono": "765434"
}

### modificar amigo
PUT http://127.0.0.1:8000/Amigos/2
Content-Type: application/json

{
    "nombre": "Pepe",
    "email": "pepe@test.com",
    "telefono": "789456"
}

### borrar amigo
DELETE http://127.0.0.1:8000/Amigos/3

